SET NAMES 'utf8mb4';

CREATE DATABASE IF NOT EXISTS shelter
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

DROP USER 'admin'@'%';
CREATE USER 'admin'@'%' IDENTIFIED BY 'zaq1@WSX';
GRANT ALL PRIVILEGES ON shelter.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

USE shelter;